const config = {
  content: [
    "./src/pages/**/*.{js,jsx,mdx}",
    "./src/components/**/*.{js,jsx,mdx}",
    "./src/app/**/*.{js,jsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        mainColor: "#F5C34B",
        secColor: "#FFAC2F",
        homeBg: "#f3f5f6",
        sidePageBg: "#F0F4F7",
        upperBarBg: "#112137",
        headerBg: "#012F47",
        figure: "#f4f4f46e",
        textDark: "#041E42",
        textLight: "#626974",
        border: "#EAEAEA",
        linksHover: "#F37521",
        error: "#ef4444",
        success: "#5cb85c ",
        disabled: "#D9D9D9",
        accordionHeader: "#EFEEE8",
        // background: "var(--background)",
        // foreground: "var(--foreground)",
        // mainColor: "var(--mainColor )",
        // secColor: "var(--secColor)",
        // homeBg: "var(--homeBg)",
        // sidePageBg: "var(--sidePageBg)",
        // upperBarBg: "var(--upperBarBg)",
        // headerBg: "var(--headerBg)",
        // figure: "var(--figure)",
        // textDark: "var(--textDark)",
        // textLight: "var(--textLight)",
        // border: "var(--border)",
        // linksHover: "var(--linksHover)",
        // error: "var(--error)",
        // success: "var(--success)",
        // disabled: "var(--disabled)",
        // accordionHeader: "var(--accordionHeader)",
      },
      fontFamily: {
        manifold: ["var(--font-manifold-cf)"],
        inter: ["var(--font-inter)", "Inter"],
      },
    },
    keyframes: {
      pumping: {
        "0%": { transform: "scale(1)" },
        "20%": { transform: "scale(0.8)" },
        "30%": { transform: "scale(1.1)" },
        "50%": { transform: "scale(1.5)" },
        "100%": { transform: "scale(1)" },
      },
    },
  },
  plugins: [],
};
export default config;
